package org.sjwimmer.tacharting.implementation.constants;

public enum Function {
    TIME_SERIES_INTRADAY,
    TIME_SERIES_DAILY,
    TIME_SERIES_DAILY_ADJUSTED,
    TIME_SERIES_WEEKLY,
    TIME_SERIES_WEEKLY_ADJUSTED,
    TIME_SERIES_MONTHLY,
    TIME_SERIES_MONTHLY_ADJUSTED,
    SYMBOL_SEARCH,
    CURRENCY_EXCHANGE_RATE,
    FX_INTRADAY,
    FX_DAILY,
    FX_WEEKLY,
    FX_MONTHLY
}
